"""Preserve locally-authored MCP servers and hook/statusline scripts.

An MCP entry like ``node C:/Users/me/mcp-servers/foo/index.js`` points at code
that exists on no registry — losing it loses the server. This collector finds
those project roots from the MCP registry, copies the *source* (never
``node_modules`` or virtualenvs), and records the command that rebuilds the
dependencies. Projects with a git remote are recorded as a clone URL instead.
"""
from __future__ import annotations

import re
from functools import lru_cache
from pathlib import Path
from typing import Any

from ..copyio import CopyError, safe_copy
from ..paths import archive_relpath, expand, portable
from ..scrub import is_secret_filename, scrub_file
from ..util import human_bytes, run
from ..walk import walk_files

#: Never copied — regenerated by the recorded rebuild command.
HEAVY = {
    "node_modules", ".venv", "venv", "env", "__pycache__", ".git", "dist", "build",
    ".next", ".turbo", ".cache", "target", ".pytest_cache", ".mypy_cache", "site-packages",
    ".tox", "Lib", "Scripts", "Include", ".ruff_cache", "coverage", ".nyc_output",
}

MARKERS = ("package.json", "pyproject.toml", "requirements.txt", "go.mod", "Cargo.toml", "setup.py")

#: Only these extensions identify an entrypoint worth tracing to a project root.
SOURCE_SUFFIXES = frozenset({".js", ".mjs", ".cjs", ".ts", ".py", ".sh", ".ps1", ".rb", ".jar"})

#: Path fragments that mean "this is a vendored runtime, not your code".
NOT_MINE = (
    "browsers", "chrome-", "chromium", "firefox-", "webkit-", "ms-playwright",
    "appdata/local/temp", "appdata\\local\\temp", "/pkgs/", "package cache",
    "windowsapps", "program files", "programdata", "/npm-cache/", "/pnpm/",
    "/.bun/install/", "/uv/tools/", "/pipx/venvs/", "system32",
)

PATH_TOKEN = re.compile(r"^[A-Za-z]:[/\\]|^[/\\]{2}|^~[/\\]|^\.{1,2}[/\\]")

MAX_PROJECT_MB = 25.0
MAX_FILE_MB = 4.0


def _looks_like_path(token: str) -> bool:
    return bool(PATH_TOKEN.match(token)) and len(token) > 3


@lru_cache(maxsize=1)
def _forbidden_roots() -> frozenset[Path]:
    """Directories that must never be treated as a single MCP project.

    The user profile often has its own ``package.json``, and tool config folders
    like ``~/.claude`` are already covered by the catalog — walking up into
    either would sweep the entire home directory into the backup.
    """
    home = expand("~")
    roots = {home, home.parent}
    if home.is_dir():
        try:
            roots.update(p for p in home.iterdir() if p.is_dir() and p.name.startswith("."))
        except OSError:
            pass
    return frozenset(roots)


def _project_root(path: Path) -> Path | None:
    """Walk up from an entrypoint to its project marker, stopping before home."""
    forbidden = _forbidden_roots()
    current = path if path.is_dir() else path.parent
    for _ in range(3):
        if current in forbidden:
            return None
        if any((current / marker).is_file() for marker in MARKERS):
            return current
        if current.parent == current:
            break
        current = current.parent

    fallback = path.parent if path.is_file() else path
    return None if fallback in forbidden else fallback


def _git_remote(root: Path) -> str | None:
    if not (root / ".git").exists():
        return None
    code, out = run(["git", "-C", str(root), "remote", "get-url", "origin"], timeout=20)
    return out.strip() if code == 0 and out.strip() else None


def _rebuild_command(root: Path) -> str:
    if (root / "pnpm-lock.yaml").is_file():
        return "pnpm install --prod=false"
    if (root / "yarn.lock").is_file():
        return "yarn install"
    if (root / "package-lock.json").is_file():
        return "npm ci"
    if (root / "package.json").is_file():
        return "npm install"
    if (root / "uv.lock").is_file():
        return "uv sync"
    if (root / "requirements.txt").is_file():
        return "python -m venv .venv; .venv\\Scripts\\pip install -r requirements.txt"
    if (root / "pyproject.toml").is_file():
        return "python -m venv .venv; .venv\\Scripts\\pip install -e ."
    if (root / "go.mod").is_file():
        return "go build ./..."
    if (root / "Cargo.toml").is_file():
        return "cargo build --release"
    return "# no dependency manifest found"


def _copy_source(root: Path, out_dir: Path) -> tuple[list[dict[str, Any]], int, list[str]]:
    """Copy the project tree minus heavy directories.

    Returns ``(captured, bytes, skipped)`` where each captured entry carries both
    the original location and its place in the archive, so the generic restore
    path can put it back without special-casing local servers.
    """
    copied: list[dict[str, Any]] = []
    skipped: list[str] = []
    total = 0
    budget = int(MAX_PROJECT_MB * 1024 * 1024)

    for path in walk_files(root):
        if is_secret_filename(path.name):
            skipped.append(f"{path.name} (credential file — excluded)")
            continue
        try:
            size = path.stat().st_size
        except OSError:
            continue
        if size > MAX_FILE_MB * 1024 * 1024:
            skipped.append(f"{path.name} ({human_bytes(size)}, over file cap)")
            continue
        if total + size > budget:
            skipped.append(f"{path.name} (project budget exhausted)")
            continue

        rel = archive_relpath(path)
        destination = out_dir / "files" / rel
        try:
            safe_copy(path, destination)
        except CopyError as exc:
            skipped.append(f"{path.name} ({exc})")
            continue
        # Server source routinely has an API key pasted into a constant.
        scrub_file(destination)
        copied.append({"source": portable(path), "archive": f"files/{rel}", "size": size})
        total += size

    return copied, total, skipped


def _is_vendored(path: Path) -> bool:
    """True for runtimes shipped by someone else — never the user's own server."""
    text = str(path).lower().replace(chr(92), "/")
    return any(fragment.replace(chr(92), "/") in text for fragment in NOT_MINE)


def _candidate_paths(server: dict[str, Any]) -> list[Path]:
    """Entrypoint scripts referenced by a stdio server's command line."""
    tokens = [server.get("command") or ""] + [str(a) for a in server.get("args") or []]
    out: list[Path] = []
    for token in tokens:
        if not _looks_like_path(token):
            continue
        candidate = expand(token)
        if not candidate.exists() or _is_vendored(candidate):
            continue
        if candidate.is_file():
            # A bare interpreter (node.exe, python.exe) is not the server's source.
            if candidate.suffix.lower() not in SOURCE_SUFFIXES:
                continue
        elif not any((candidate / marker).is_file() for marker in MARKERS):
            # Directory arguments are usually data roots handed to a server
            # (filesystem, memory); only a real project directory counts.
            continue
        out.append(candidate)
    return out


def _find_projects(mcp_registry: dict[str, Any]) -> dict[str, dict[str, Any]]:
    """Locate every local MCP server implementation referenced by any client."""
    projects: dict[str, dict[str, Any]] = {}

    for server in mcp_registry.get("servers", []):
        if server.get("transport") not in (None, "stdio"):
            continue
        for candidate in _candidate_paths(server):
            root = _project_root(candidate)
            if root is None or not root.is_dir():
                continue
            # Skip anything living inside a package manager's or vendor's own tree.
            if set(root.parts) & HEAVY or _is_vendored(root):
                continue
            key = str(root).lower()
            entry = projects.setdefault(key, {
                "name": root.name,
                "path": portable(root),
                "used_by_servers": [],
                "entrypoints": [],
            })
            if server["name"] not in entry["used_by_servers"]:
                entry["used_by_servers"].append(server["name"])
            if portable(candidate) not in entry["entrypoints"]:
                entry["entrypoints"].append(portable(candidate))

    return projects


def discover(mcp_registry: dict[str, Any]) -> dict[str, Any]:
    """List local MCP servers without copying anything (Demo edition)."""
    projects = []
    for entry in _find_projects(mcp_registry).values():
        root = expand(entry["path"])
        projects.append({
            **entry,
            "git_remote": _git_remote(root),
            "rebuild": _rebuild_command(root),
            "strategy": "listed only (Premium copies the source)",
            "copied_files": 0,
            "copied_bytes": 0,
            "captured": [],
        })
    projects.sort(key=lambda p: p["name"].lower())
    return {
        "project_count": len(projects),
        "note": "Demo edition — source not copied. Premium captures these projects in full.",
        "projects": projects,
    }


def collect(mcp_registry: dict[str, Any], out_dir: Path) -> dict[str, Any]:
    """Back up every local MCP server implementation referenced by any client."""
    projects = _find_projects(mcp_registry)

    results: list[dict[str, Any]] = []
    for entry in projects.values():
        root = expand(entry["path"])
        remote = _git_remote(root)
        entry["git_remote"] = remote
        entry["rebuild"] = _rebuild_command(root)

        if remote:
            entry["strategy"] = "clone"
            entry["restore"] = [f"git clone {remote} {entry['path']}", f"cd {entry['path']}", entry["rebuild"]]
            entry["copied_files"] = 0
            entry["copied_bytes"] = 0
            entry["captured"] = []
        else:
            copied, size, skipped = _copy_source(root, out_dir)
            entry["strategy"] = "copied source"
            entry["copied_files"] = len(copied)
            entry["copied_bytes"] = size
            entry["skipped"] = skipped
            entry["captured"] = copied
            entry["restore"] = [f"# source restored to {entry['path']}", f"cd {entry['path']}", entry["rebuild"]]
        results.append(entry)

    results.sort(key=lambda p: p["name"].lower())
    return {
        "project_count": len(results),
        "note": "Dependencies (node_modules, virtualenvs) are never copied — rerun the rebuild command.",
        "projects": results,
    }
